# File to DO EDA on the Intensities dataset

### Constants

In [21]:
from enum import Enum
DATASET_DIR = "data/clean/intensities_t1.csv"

class Features(Enum):
	"""
	Enumeration of the features in the dataset.
	Attributes:
		MAGNITUDE (str): The magnitude of the earthquake.
		DEPTH (str): The depth of the earthquake.
		RHYPO (str): The hypocenter of the earthquake.
		REGIME (str): The regime of the earthquake.	
		MMI (str): The Modified Mercalli Intensity of the earthquake.
	"""
	MAGNITUDE = "magnitude"
	DEPTH = "depth"
	RHYPO = "rhypo"
	REGIME = "regime"
	MMI = "mmi"

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(DATASET_DIR)

In [23]:
df.shape

(672059, 5)

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 672059 entries, 0 to 672058
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   magnitude  672059 non-null  float64
 1   depth      672059 non-null  float64
 2   rhypo      672059 non-null  float64
 3   regime     672059 non-null  str
 4   mmi        672059 non-null  float64
dtypes: float64(4), str(1)
memory usage: 25.6 MB

In [25]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
magnitude,672059.0,4.417009,1.045178,3.000000,3.600000,4.19000,4.99000,7.300
depth,672059.0,10.772898,6.620701,-3.340000,7.302000,9.99000,13.05100,76.200
rhypo,672059.0,88.566661,97.139229,0.562028,26.250605,53.61232,117.41855,1834.186
mmi,672059.0,2.871118,0.954398,1.000000,2.200000,2.70000,3.40000,9.100

In [26]:
df.head()

   magnitude  depth      rhypo      regime  mmi
0       4.16  0.477   2.129752      active  5.8
1       5.01  1.480   2.670254      active  5.8
2       7.30 -0.097  10.555350      active  7.9
3       5.10  2.800   3.029873  subduction  6.7
4       5.01  1.480   2.307831      active  6.1

In [31]:
print( df[df[Features.DEPTH.value] <=0 ])

        magnitude  depth      rhypo      regime  mmi
2            7.30 -0.097  10.555350      active  7.9
15           7.30 -0.097  12.698090      active  7.9
17           7.30 -0.097   2.414935      active  7.2
27           7.30 -0.097   7.792499      active  6.2
33           4.06 -0.650   1.084711      active  3.4
...           ...    ...        ...         ...  ...
669790       3.17 -0.270   1.700399  subduction  4.3
669930       3.10 -1.070   1.450079      active  4.7
670124       3.50  0.000   1.868298      active  2.0
670518       3.10 -1.070   1.254744      active  2.6
670927       3.10 -1.070   1.129976      active  2.0

[5903 rows x 5 columns]